//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.Employes_Sessions = new HashSet<Employes_Sessions>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<int> salaire { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string typeMetier { get; set; }
        public string Metier { get; set; }
    
        public virtual ICollection<Employes_Sessions> Employes_Sessions { get; set; }
    }
}
