//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes_Sessions
    {
        public int id { get; set; }
        public Nullable<int> idEmploye { get; set; }
        public Nullable<int> idSession { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Session Session { get; set; }
    }
}
